### ISSUE TITLE
error in BERT_evel.ipynb

### ISSUE THREAD

**Issue by jxy-001** [ThilinaRajapakse/BERT_binary_text_classification#11]
tmp_eval_loss = loss_fct(logits.view(-1, num_labels), label_ids.view(-1))

AttributeError: 'tuple' object has no attribute 'view'

**Comment by ThilinaRajapakse** [comment]
You are getting this because you are using the updated BERT library. There the model outputs are tuples.
Change the line from:
`logits = model(input_ids, segment_ids, input_mask, labels=None)`

to:
`logits = model(input_ids, segment_ids, input_mask, labels=None)[0]`

See #9

**Comment by jxy-001** [comment]
thanks a lot!
