### ISSUE TITLE
Model name 'cache/yelp.tar.gz' was not found in model name li

### ISSUE THREAD

**Issue by tianke0711** [ThilinaRajapakse/BERT_binary_text_classification#12]
The BERT_eval.ipynb, in the In [29]: there is error: 

`ERROR:pytorch_pretrained_bert.modeling:Model name 'cache/yelp.tar.gz' was not found in model name list (bert-base-uncased, bert-large-uncased, bert-base-cased, bert-large-cased, bert-base-multilingual-uncased, bert-base-multilingual-cased, bert-base-chinese). We assumed 'cache/yelp.tar.gz' was a path or url but couldn't find any file associated to this path or url.`

I think you didn't save the mode weight as "yelp.tar.gz" in the BERT.ipynb, Please check it.

Thanks!

**Comment by ThilinaRajapakse** [comment]
> 1. Go into the outputs/yelp directory where the fine tuned models will be saved. There, you should find 3 files; config.json, pytorch_model.bin, vocab.txt.
> 2. Archive the two files (I use 7zip for archiving) config.json, and pytorch_model.bin into a .tar file.
> 3. Compress the .tar file into gzip format. Now the file should be something like yelp.tar.gz
> 4. Copy the compressed file into the cache/ directory.

From the [article](https://medium.com/swlh/a-simple-guide-on-using-bert-for-text-classification-bbf041ac8d04).
