### ISSUE TITLE
use my own rumor datasets,but .......

### ISSUE THREAD

**Issue by jxy-001** [ThilinaRajapakse/BERT_binary_text_classification#13]
![Screenshot_2019-08-20 Untitled](https://user-images.githubusercontent.com/54132123/63348961-fda81680-c38c-11e9-9b30-af24cc867535.png)
![Screenshot_2019-08-20 BERT_eval](https://user-images.githubusercontent.com/54132123/63349092-465fcf80-c38d-11e9-99ca-2fdc3d756bbc.png)
I can't find the reason，could  you give me a hand? Thank you！

**Comment by ThilinaRajapakse** [comment]
Make sure you've made this #11 change in the training dataset as well. Other than that, it's hard to say without knowing more.

**Comment by jxy-001** [comment]
May I ask if you have time to test my datasets？

**Comment by ThilinaRajapakse** [comment]
Send me a small sample and I'll see what I can do.

**Comment by jxy-001** [comment]
[liar.zip](https://github.com/ThilinaRajapakse/BERT_binary_text_classification/files/3520838/liar.zip)
thanks a lot!!

**Comment by ThilinaRajapakse** [comment]
```
INFO:__main__:***** Eval results  *****
INFO:__main__:  fn = 412
INFO:__main__:  fp = 96
INFO:__main__:  mcc = 0.1532762065141828
INFO:__main__:  tn = 618
INFO:__main__:  tp = 141
```

I get bad results from your data as well. It looks like you have a bad dataset. If you want, you can try the [Yelp dataset](https://s3.amazonaws.com/fast-ai-nlp/yelp_review_polarity_csv.tgz).
