### ISSUE TITLE
fine-tuned vocab.txt

### ISSUE THREAD

**Issue by vr25** [ThilinaRajapakse/BERT_binary_text_classification#19]
Hi,

After fine-tuning on yelp dataset using the bert-base-cased, I found that it saved the exact vocab.txt as the one in the bert-base-cased. I was wondering if the tokenizer needs to be initialized again for the fine-tuned model. I consolidated all the code in different notebooks into a single file (attached here). Please let me know if I should have a separate script for loading the fine-tuned model. 
[BERT_train_py.txt](https://github.com/ThilinaRajapakse/BERT_binary_text_classification/files/3748296/BERT_train_py.txt)

**Comment by ThilinaRajapakse** [comment]
Yes, the `vocab` file is the same. The tokenizer is needed anytime you are doing training or inference to convert text into features.

**Comment by vr25** [comment]
Alright, thanks!
