### ISSUE TITLE
License issue; can I reuse your code?

### ISSUE THREAD

**Issue by jeromebedard12** [ThilinaRajapakse/BERT_binary_text_classification#20]
I would like to reuse some of your code for a demo but your project doesn't seem to be published under any license. Would you be willing to add one?

Thank you,

Jerome

https://help.github.com/en/github/building-a-strong-community/adding-a-license-to-a-repository

**Comment by ThilinaRajapakse** [comment]
Done.

Just as a heads up, this repo works with an older version of the Hugging Face Transformers library. The updated repo [here](https://github.com/ThilinaRajapakse/pytorch-transformers-classification) is quite similar to this one, except that it uses the updated version of the library (and has cleaner code).

_If you prefer a ready to use library, there's also [this](https://github.com/ThilinaRajapakse/simpletransformers)._

**Comment by jeromebedard12** [comment]
Thank you!
