### ISSUE TITLE
Evaluation report missing

### ISSUE THREAD

**Issue by Magpi007** [ThilinaRajapakse/BERT_binary_text_classification#3]
Hi Thiilina,

Just finished to reproduce the code, and at the end of the evaluation process, I got this error message just after finishing the process and before printing the results. :

<img width="960" alt="Untitled" src="https://user-images.githubusercontent.com/50815888/62676412-c753ba00-b9d0-11e9-855a-6bb3d9bf70b9.png">

I have navigated through the folders created by the code but I can't find the file 'eval_results.txt'. The only thing I have seen is that the code tries to store the report file in a folder called 'insults_evaluation_reports' (note reports is plural), but the system has the folder 'insults_evaluation_report' (in singular) and a subfolder called 'report_0' that is empty as you can see in the attached screenshot. In the 'insults_evaluation_report' folder there is aren't files, only the folder 'report_0'. Any idea where can I find the file?

Thanks!

**Comment by ThilinaRajapakse** [comment]
Continued in https://github.com/ThilinaRajapakse/BERT_binary_text_classification/issues/4.
