### ISSUE TITLE
Error when loading pre-trained model in the Evaluation

### ISSUE THREAD

**Issue by Magpi007** [ThilinaRajapakse/BERT_binary_text_classification#6]
Hi Thilina:

I am now running the model using a local machine (I previously run it in colab). I have been able to implement all the steps, but in the Evaluation part, when I execute the following line:

`model = BertForSequenceClassification.from_pretrained(CACHE_DIR + BERT_MODEL, cache_dir=CACHE_DIR, num_labels=num_labels)`

I got this error:

<img width="960" alt="Untitled" src="https://user-images.githubusercontent.com/50815888/63140726-f689ad00-c008-11e9-90b5-23635b2158ed.png">

The previous process looks for the 'bert_config.json' file in the temporary folder, and I have checked the folder and is not there. Instead, in this temporary folder there is a folder called 'output' and inside this folder another folder called 'insult' (that is the name I gave to the TASK_NAME variable), where you can find two files: 'config.json' and 'pytorch_model.bin'. 

I can't see the place where the process looks for this files. I am a bit stuck here as the code is the same that worked in colab. Do you know what can be?

Just in case it matters I am executing it in W10 + Anaconda environment.

Thanks.

**Comment by ThilinaRajapakse** [comment]
Go inside the 'insult' directory, and compress the two files (`config.json` and `pytorch_model.bin`) into `.tar.gz` format (e.g. `insult.tar.gz`). Move the archive into the `cache/` directory. This is the default path checked in BERT_eval.
If you want to change it, the path is built by concatenating the two string `CACHE_DIR` and `BERT_MODEL` found in the second cell. This path should point to your compressed file (`<something>.tar.gz`) containing `config.json` and `pytorch_model.bin`. In other words, the model is loaded from the relative path (starting from the notebook location) `<CACHE_DIR>/<BERT_MODEL>.tar.gz`.

**Comment by Magpi007** [comment]
Sometimes we focus on the most complex parameters and forgot the more simple ones... Sorry I created the .tar.gz file with the folder structure so the modeling.py was not able to locate it. Already fixed and working well. Thanks.
