### ISSUE TITLE
Error when reading in fine_tuned model for BERT_eval.py

### ISSUE THREAD

**Issue by Seohyeong** [ThilinaRajapakse/BERT_binary_text_classification#7]
I've compressed bert_config.json and pytorch_model.bin files into yelp.tar.gz. However, when I run 

`model = BertForSequenceClassification.from_pretrained(CACHE_DIR + BERT_MODEL, cache_dir=CACHE_DIR, num_labels=len(label_list))` 

line from BERT_eval.py it gives me an error (I'm posting other printed output as well in case it helps.)

`INFO:pytorch_pretrained_bert.tokenization:loading vocabulary file outputs/yelp/vocab.txt
INFO:pytorch_pretrained_bert.modeling:loading archive file cache/yelp.tar.gz
INFO:pytorch_pretrained_bert.modeling:extracting archive file cache/yelp.tar.gz to temp dir /tmp/tmpp1bpnj8s
INFO:pytorch_pretrained_bert.modeling:Model config {
  "attention_probs_dropout_prob": 0.1,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "max_position_embeddings": 512,
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "type_vocab_size": 2,
  "vocab_size": 28996
}`

`Traceback (most recent call last):
  File "/home/seohyeong/.pycharm_helpers/pydev/pydevd.py", line 2060, in <module>
    main()
  File "/home/seohyeong/.pycharm_helpers/pydev/pydevd.py", line 2054, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/seohyeong/.pycharm_helpers/pydev/pydevd.py", line 1405, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "/home/seohyeong/.pycharm_helpers/pydev/pydevd.py", line 1412, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/seohyeong/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/seohyeong/Dropbox/Naver/Pretrained_BERT/BERT_eval.py", line 155, in <module>
    model = BertForSequenceClassification.from_pretrained(CACHE_DIR + BERT_MODEL, cache_dir=CACHE_DIR, num_labels=len(label_list))
  File "/home/seohyeong/anaconda3/envs/nlp/lib/python3.6/site-packages/pytorch_pretrained_bert/modeling.py", line 603, in from_pretrained
    state_dict = torch.load(weights_path, map_location='cpu')
  File "/home/seohyeong/anaconda3/envs/nlp/lib/python3.6/site-packages/torch/serialization.py", line 386, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/home/seohyeong/anaconda3/envs/nlp/lib/python3.6/site-packages/torch/serialization.py", line 563, in _load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '\x1f'.`

I've compressed config.json and model.bin together into tar.gz without folder structure on ubuntu machine using `tar -czvf` command. It seems like unpickling error is coming from loading weights from pytorch_model.bin in yelp.tar.gz. I have no idea what's triggering this error tho. Do you have any idea?

**Comment by ThilinaRajapakse** [comment]
Does it work if you try it with a freshly downloaded pre-trained BERT model from the library? For example, taking the downloaded files and placing them in the directory and loading it through the eval notebook.
Are you using the old `pytorch-pretrained-bert` or the new version `pytorch-transformers`? This repo was written with the old version, i.e. `pytorch-pretrained-bert`.

**Comment by Seohyeong** [comment]
Modeling loading part from BERT.py `model = BertForSequenceClassification.from_pretrained(BERT_MODEL, cache_dir=CACHE_DIR, num_labels=num_labels)` works fine. The error occurs when loading the fine-tuned model (yelp.tar.gz according to your medium post). And yes, I'm using `pytorch_pretrained_bert`. 

Did you also directly compressed pytorch_model.bin and config.json files into yelp.tar.gz (I did)? Or should I zip two files into tar first and then convert it to .gz format?

**Comment by ThilinaRajapakse** [comment]
It shouldn't really matter how you compress the files, but I guess it wouldn't hurt to try.
I can't really think of a reason why this wouldn't work unless the model file was damaged somehow. Can you try training a model on a very small dataset and check whether you can load the model generated from that?

**Comment by Seohyeong** [comment]
I've tried with the smaller dataset and I got no error. I guess pytorch_model.bin file somehow got damaged. I'll try again with the YELP dataset again! Thanks.

**Comment by ThilinaRajapakse** [comment]
Great!
